import os

variable_list = [
  { "value": { "value": os.getenv("DOMAIN_NAME") }, "context": "Default", "name": "domain_name" },
  { "value": { "value": os.getenv("OCP_BASE_DOMAIN") }, "context": "Default", "name": "ocp_base_domain" },
  { "value": { "value": os.getenv("DNS") }, "context": "Default", "name": "dns_server" },
  { "value": { "value": os.getenv("NUTANIX_FILES_NFS_FQDN") }, "context": "Default", "name": "nutanix_files_nfs_fqdn" },
  { "value": { "value": os.getenv("NUTANIX_FILES_NFS_EXPORT") }, "context": "Default", "name": "nutanix_files_nfs_export" },
  { "value": { "value": os.getenv("PC_PORT") }, "context": "Default", "name": "pc_instance_port" },
  { "value": { "value": os.getenv("OCP_NTNX_PC_DNS_FQDN") }, "context": "Default", "name": "ocp_ntnx_pc_dns_fqdn" },
  { "value": { "value": os.getenv("NTNX_PC_IP") }, "context": "Default", "name": "pc_instance_ip" },
  { "value": { "value": os.getenv("OCP_INFRA_REPLICA_COUNT") }, "context": "Default", "name": "infra_machineset_count" },
  { "value": { "value": os.getenv("OCP_WORKER_REPLICA_COUNT") }, "context": "Default", "name": "worker_machineset_count" },
  { "value": { "value": os.getenv("OCP_CONTROL_PLANE_REPLICA_COUNT") }, "context": "Default", "name": "control_plane_count" },
  { "value": { "value": os.getenv("NTNX_PE_STORAGE_CONTAINER") }, "context": "Default", "name": "storage_container_name" },
  { "value": { "value": os.getenv("NTNX_PE_VLAN") }, "context": "Default", "name": "network" },
  { "value": { "value": os.getenv("PE_CLUSTER_NAME") }, "context": "Default", "name": "nutanix_ahv_cluster" },
  { "value": { "value": os.getenv("OCP_CLUSTER_NAME") }, "context": "Default", "name": "ocp_cluster_name"},
  { "value": { "value": os.getenv("OCP_HUB_CLUSTER_NAME") }, "context": "Default", "name": "ocp_hub_cluster_name"},
  { "value": { "value": os.getenv("OCP_API_VIP") }, "context": "Default", "name": "api_ipv4_vip" },
  { "value": { "value": os.getenv("OCP_APPS_INGRESS_VIP") }, "context": "Default", "name": "wildcard_ingress_ipv4_vip" },
  { "value": { "value": os.getenv("OBJECTS_BUCKETS_LIST") }, "context": "Default", "name": "objects_buckets_list" },
  { "value": { "value": os.getenv("OBJECTS_STORE_DNS_FQDN") }, "context": "Default", "name": "objects_store_dns_fqdn" },
  { "value": { "value": os.getenv("OCP_PULL_SECRET_JSON") }, "context": "Default", "name": "ocp_pull_secret" },
  { "value": { "value": os.getenv("ENABLE_REDHAT_ADVANCED_CLUSTER_MGMT") }, "context": "Default", "name": "enable_redhat_advanced_cluster_management" },
  { "value": { "value": os.getenv("IMPORT_OCP_MANAGED_CLUSTER") }, "context": "Default", "name": "import_ocp_managed_cluster" },
  { "value": { "value": os.getenv("ERA_VM_IP") }, "context": "Default", "name": "era_vm_ip" },
  #{ "value": { "value": "false" }, "context": "Default", "name": "autoscaler_enabled" },
  #{ "value": { "value": "1" }, "context": "Default", "name": "addtl_worker_count" },
  #{ "value": { "value": "1" }, "context": "Default", "name": "less_worker_count" },
  #{ "value": { "value": "5" }, "context": "Default", "name": "autoscaler_max_count" },
]
