### Set endpoint
@contentType = application/json
@accept = application/json
@base_url = https://{{pc-ip}}:9440/

## Set Variables

@cluster_name = PHX-SPOC020-2
@storage_container_name = Default

### Get Clusters
# @name clusters
GET {{base_url}}/api/clustermgmt/v4.0.a2/config/clusters?$filter=name eq '{{cluster_name}}'
Authorization: Basic {{basic_auth_token}}

@cluster_ext_id={{clusters.response.body.data[0].extId}}

### Get Storage_Containers
# @name storage_containers
GET {{base_url}}/api/storage/v4.0.a3/config/storage-containers?$filter=name eq '{{storage_container_name}}' and clusterExtId eq '{{cluster_ext_id}}'
Authorization: Basic {{basic_auth_token}}

@storage_container_uuid={{storage_containers.response.body.data[0].containerExtId}}
 