kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
  image: kindest/node:v1.22.5
- role: worker
  image: kindest/node:v1.22.5
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  image: kindest/node:v1.22.5
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
networking:
  #podSubnet: 192.168.0.0/16 # set to Calico's default subnet
  podSubnet: "10.2.0.0/16"
  serviceSubnet: "10.3.0.0/16"
  disableDefaultCNI: true