## 1. .rest files require rest client vscode extension.
## 2. get basic auth token `echo -n admin:nutanix/4u | base64`
## 3. update rest-client.enviornmentVariables and rest-client.defaultHeaders in vscode settings.json
# "rest-client.environmentVariables": {
#   "kalm-main-11-1": {
#     "pe_ip": "10.38.11.7",
#     "pc_ip": "10.38.11.9",
#     "basic_auth_token": "admin:nutanix/4u",
#     "karbon_cluster_name": "kalm-main-11-1"
#   }
# },
# "rest-client.defaultHeaders": {
#    "User-Agent": "vscode-restclient",
#    "Content-Type": "application/json"
# },
## 4. easily switch between environments via command palette Rest Client: Switch Environment  (ctrl-shift-P)
## 5. send request via command palette option Rest Client: Send Request (ctrl-shift-P)

# - v0.8 Options
#   - ha
#   - hosts
#   - images
#   - networks
#   - snapshots
#   - tasks
#   - vdisks
#   - vms
#   - volume_groups

@base_url = https://{{pe_ip}}:9440/api/nutanix/v0.8


### Get a list of KVM managed Virtual Machines.
# @name vms
GET {{base_url}}/vms
Authorization: Basic {{basic_auth_token}}


