|-
#cloud-config
hostname: @@{name}@@
users:
  - name: @@{Nutanix.username}@@
    shell: /bin/bash
    homedir: /home/@@{Nutanix.username}@@
    ssh-authorized-keys:
      - @@{nutanix_public_key}@@
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
runcmd:
    - yum install -y lvm2
